# Generated by Django 5.2.15 on 2026-07-18 07:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.accounts.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Designates that this user has all permissions without "
                            "explicitly assigning them."
                        ),
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=32, unique=True)),
                ("username_changed_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("phone_e164", models.CharField(blank=True, max_length=20, null=True)),
                ("phone_verified_at", models.DateTimeField(blank=True, null=True)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text=(
                            "The groups this user belongs to. A user will get all "
                            "permissions granted to each of their groups."
                        ),
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            managers=[
                ("objects", apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="BenefitClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[("welcome_signup", "Welcome signup")], max_length=64
                    ),
                ),
                ("phone_hash", models.CharField(blank=True, max_length=128, null=True)),
                ("email_hash", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "social_identity_hash",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("claimed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("claim_source", models.CharField(max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="benefit_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_email", models.EmailField(max_length=254)),
                ("token_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("kakao", "Kakao"), ("naver", "Naver")], max_length=20
                    ),
                ),
                ("provider_user_id", models.CharField(max_length=255)),
                (
                    "provider_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("provider_email_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("linked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("anonymized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("email_verify", "Email verify"),
                            ("password_set", "Password set"),
                            ("password_reset", "Password reset"),
                        ],
                        max_length=32,
                    ),
                ),
                ("token_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("phone_verified_at__isnull", False)
                ),
                fields=("phone_e164",),
                name="accounts_user_verified_phone_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="benefitclaim",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("code", "welcome_signup"), _negated=True),
                    ("phone_hash__isnull", False),
                    _connector="OR",
                ),
                name="accounts_benefit_welcome_requires_phone_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="benefitclaim",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("code", "welcome_signup"), ("phone_hash__isnull", False)
                ),
                fields=("code", "phone_hash"),
                name="accounts_benefit_welcome_phone_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="emailchangerequest",
            index=models.Index(
                fields=["user", "confirmed_at", "expires_at"],
                name="accounts_em_user_id_96ba00_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailchangerequest",
            index=models.Index(
                fields=["token_hash"], name="accounts_em_token_h_c1c4e2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="socialaccount",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_user_id"),
                name="accounts_social_provider_identity_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="socialaccount",
            constraint=models.UniqueConstraint(
                fields=("user", "provider"), name="accounts_social_user_provider_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="usertoken",
            index=models.Index(
                fields=["user", "purpose", "consumed_at", "expires_at"],
                name="accounts_us_user_id_75ce9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usertoken",
            index=models.Index(
                fields=["token_hash"], name="accounts_us_token_h_d89c2d_idx"
            ),
        ),
    ]
