# Generated by Django 5.2.15 on 2026-07-20 12:02

import apps.accounts.managers
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시간')),
                ('email', models.EmailField(help_text='로그인에 사용하는 대표 이메일', max_length=254, unique=True)),
                ('username', models.CharField(help_text='고객에게 노출 가능한 고유 사용자명', max_length=32, unique=True)),
                ('username_changed_at', models.DateTimeField(blank=True, help_text='사용자명 마지막 변경 시간', null=True)),
                ('name', models.CharField(blank=True, help_text='고객 실명 또는 표시 이름', max_length=100)),
                ('phone_e164', models.CharField(blank=True, help_text='SMS 인증 후 저장되는 E.164 전화번호', max_length=20, null=True)),
                ('phone_verified_at', models.DateTimeField(blank=True, help_text='전화번호 인증 완료 시간', null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, help_text='대표 이메일 인증 완료 시간', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='로그인 가능한 활성 계정 여부')),
                ('is_staff', models.BooleanField(default=False, help_text='관리자 사이트와 관리자 API 접근 여부')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='계정 탈퇴 또는 비활성 처리 시간', null=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, help_text='가입 시간')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BenefitClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('welcome_signup', 'Welcome signup')], help_text='혜택 코드', max_length=64)),
                ('phone_hash', models.CharField(blank=True, help_text='전화번호 HMAC 해시', max_length=128, null=True)),
                ('claimed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='혜택 지급 시간')),
                ('claim_source', models.CharField(help_text='혜택 지급 트리거 출처', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='혜택 지급 관련 추가 정보')),
                ('user', models.ForeignKey(blank=True, help_text='혜택을 받은 사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benefit_claims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(help_text='변경하려는 새 대표 이메일', max_length=254)),
                ('token_hash', models.CharField(help_text='이메일 변경 확인 토큰 해시', max_length=128)),
                ('expires_at', models.DateTimeField(help_text='요청 만료 시간')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='새 이메일 확인 완료 시간', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='요청 생성 시간')),
                ('user', models.ForeignKey(help_text='이메일 변경을 요청한 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='email_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시간')),
                ('provider', models.CharField(choices=[('kakao', 'Kakao'), ('naver', 'Naver')], help_text='소셜 로그인 제공자', max_length=20)),
                ('provider_user_id', models.CharField(help_text='제공자가 발급한 사용자 식별자', max_length=255)),
                ('provider_email', models.EmailField(blank=True, help_text='제공자가 전달한 이메일 스냅샷', max_length=254, null=True)),
                ('provider_email_verified', models.BooleanField(default=False, help_text='제공자 기준 이메일 인증 여부')),
                ('is_active', models.BooleanField(default=True, help_text='로그인 lookup에 사용할 수 있는 연결 여부')),
                ('linked_at', models.DateTimeField(default=django.utils.timezone.now, help_text='소셜 계정 연결 시간')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='소셜 연결 해제 또는 탈퇴 처리 시간', null=True)),
                ('user', models.ForeignKey(help_text='소셜 계정이 연결된 내부 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('email_verify', 'Email verify'), ('password_set', 'Password set'), ('password_reset', 'Password reset')], help_text='토큰 사용 목적', max_length=32)),
                ('token_hash', models.CharField(help_text='일회성 토큰 해시', max_length=128)),
                ('expires_at', models.DateTimeField(help_text='토큰 만료 시간')),
                ('consumed_at', models.DateTimeField(blank=True, help_text='토큰 사용 완료 시간', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='토큰 생성 시간')),
                ('user', models.ForeignKey(help_text='토큰이 귀속된 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('phone_verified_at__isnull', False)), fields=('phone_e164',), name='accounts_user_verified_phone_unique'),
        ),
        migrations.AddConstraint(
            model_name='benefitclaim',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('code', 'welcome_signup'), _negated=True), ('phone_hash__isnull', False), _connector='OR'), name='accounts_benefit_welcome_requires_phone_hash'),
        ),
        migrations.AddConstraint(
            model_name='benefitclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('code', 'welcome_signup'), ('phone_hash__isnull', False)), fields=('code', 'phone_hash'), name='accounts_benefit_welcome_phone_unique'),
        ),
        migrations.AddIndex(
            model_name='emailchangerequest',
            index=models.Index(fields=['user', 'confirmed_at', 'expires_at'], name='accounts_em_user_id_96ba00_idx'),
        ),
        migrations.AddIndex(
            model_name='emailchangerequest',
            index=models.Index(fields=['token_hash'], name='accounts_em_token_h_c1c4e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='accounts_social_provider_identity_unique'),
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='accounts_social_user_provider_unique'),
        ),
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['user', 'purpose', 'consumed_at', 'expires_at'], name='accounts_us_user_id_75ce9a_idx'),
        ),
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['token_hash'], name='accounts_us_token_h_d89c2d_idx'),
        ),
    ]
