# Generated by Django 5.2.15 on 2026-08-19 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="joined_at",
        ),
    ]
