# Generated by Django 5.2.15 on 2026-08-19 12:33

from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Lower


def validate_case_insensitive_email_uniqueness(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    duplicate_emails = list(
        User.objects.exclude(email="")
        .annotate(normalized_email=Lower("email"))
        .values("normalized_email")
        .annotate(user_count=Count("id"))
        .filter(user_count__gt=1)
        .values_list("normalized_email", flat=True)
    )
    if duplicate_emails:
        duplicates = ", ".join(sorted(duplicate_emails))
        raise RuntimeError(
            "Cannot normalize account emails because case-insensitive duplicates "
            f"exist: {duplicates}"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_user_joined_at"),
    ]

    run_before = [("account", "0006_emailaddress_lower")]

    operations = [
        migrations.RunPython(
            validate_case_insensitive_email_uniqueness,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, help_text="staff 기능 접근 여부"),
        ),
    ]
