# Generated by Django 5.2.15 on 2026-08-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_user_joined_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, help_text="staff 기능 접근 여부"),
        ),
    ]
