# Generated by Django 6.1.1 on 2026-09-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_move_auth_state_to_allauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, help_text='마지막 로그인 시간', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Django password hasher 결과', max_length=128),
        ),
    ]
