services:
  app:
    build:
      target: development
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_DEBUG: "true"
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  db:
    ports:
      - "5432:5432"
